name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: 
          sudo apt-get remove g++;
          sudo apt-get install -y cmake g++-9
      - name: CMake
        run:
          chmod +x ./build;
          ./build      
      - name: Make
        run: cd out &&make
      - name: Package
        run: cd out &&make package
      - uses: actions/checkout@v2

  chore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: Install
        run: 
          sudo npm install -g yarn;
          yarn;
      - name: Changelog
        run: yarn run version
      - name: Commit
        run: 
          git config --global user.email "small-pony@qq.com";
          git config --global user.name "hydrioner";
          git commit -m "(Github Action) Update changelog"
      - name: Push
        run: git push
      - uses: actions/checkout@v2